// The service graph: what the bank can do, as a map agents can walk.
// Curated by domain experts, not generated. Candidate generation over this graph
// is deterministic; the LLM only writes the words.
import type { ServiceNode } from "./types";

const infoOk = { type: "info", ackLabel: "Got it", dismissLabel: "Not helpful" } as const;

export const SERVICE_GRAPH: ServiceNode[] = [
  {
    id: "budget_coach", name: "Budget coach", branch: "budgeting", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [
      { watcher: "category_shift", category: "groceries", direction: "up" },
      { watcher: "category_shift", category: "restaurants", direction: "up" },
      { watcher: "category_shift", category: "shopping", direction: "up" },
    ],
    hard: [], soft: ["Spending shift is sustained, not a one-off", "Customer hasn't declared the change as intended"],
    requires: [], unlocks: ["rule_alert"], conflicts: [],
    procedure: ["Ask how the customer sees the change", "Declare as new normal / temporary", "Or compile a weekly spending rule"],
    freedoms: ["weekly limit amount", "warning threshold"],
    customerValue: 0.7, kbcValue: 0.05, urgency: 0.55,
    component: { type: "choice", options: [
      { id: "new_normal", label: "It's the new normal" },
      { id: "temporary", label: "Just temporary" },
      { id: "help", label: "Help me get back under {weekly}/week" },
    ] },
    copy: {
      title: "Your {category} spending is up {pct}%",
      body: "Last 30 days: {recent} vs your usual {baseline}. Is this a new normal, something temporary, or should I help you get back under {weekly} a week?",
    },
  },
  {
    id: "subscription_review", name: "Subscription overview", branch: "budgeting", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "new_recurring", category: "subscriptions" }],
    hard: [], soft: ["Total subscriptions high relative to income"], requires: [], unlocks: [], conflicts: [],
    procedure: ["List active subscriptions", "Offer to flag unused ones"], freedoms: [],
    customerValue: 0.25, kbcValue: 0, urgency: 0.2,
    component: infoOk,
    copy: { title: "New subscription: {merchant}", body: "You now pay {amount}/month to {merchant}. Your subscriptions add up to {subsTotal}/month." },
  },
  {
    id: "pet_budget", name: "New fixed cost: pet", branch: "pets", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "new_recurring", category: "pets" }],
    hard: [], soft: [], requires: [], unlocks: ["pet_insurance"], conflicts: [],
    procedure: ["Add to fixed costs", "Update the monthly budget"], freedoms: [],
    customerValue: 0.55, kbcValue: 0, urgency: 0.35,
    component: infoOk,
    copy: { title: "New monthly cost: {merchant}", body: "{amount}/month is now part of your fixed costs, which come to {fixedCosts} a month. Your budget has been updated." },
  },
  {
    id: "pet_insurance", name: "Pet insurance", branch: "pets", kind: "offer", commercial: true, guardrail: "self_serve",
    triggers: [{ belief: "household.pet" }],
    hard: [{ type: "age_min", value: 18 }, { type: "not_product", product: "pet_insurance" }],
    soft: ["New pet in the household", "Recurring vet costs", "Budget room for a premium"],
    requires: ["current_account"], unlocks: [], conflicts: [],
    procedure: ["Show coverage levels", "Quote online", "Sign digitally"], freedoms: ["coverage level", "deductible"],
    customerValue: 0.6, kbcValue: 0.7, urgency: 0.5,
    component: { type: "confirm", confirmLabel: "Show me options", declineLabel: "Not now" },
    copy: { title: "Looks like you have a new pet", body: "Vet costs for a young dog easily reach a few hundred euro a year. Pet insurance covers accidents and illness from about €10/month. Want to see what it would cover?" },
  },
  {
    id: "car_insurance", name: "Car insurance", branch: "mobility", kind: "offer", commercial: true, guardrail: "self_serve",
    triggers: [{ belief: "mobility.car" }],
    hard: [{ type: "age_min", value: 18 }, { type: "not_product", product: "car_insurance" }],
    soft: ["Recent car purchase", "Fuel payments started"], requires: ["current_account"], unlocks: [], conflicts: [],
    procedure: ["Enter licence plate", "Choose coverage", "Sign and receive the insurance certificate"], freedoms: ["omnium level", "deductible"],
    customerValue: 0.7, kbcValue: 0.75, urgency: 0.85,
    component: { type: "confirm", confirmLabel: "Get a quote in 2 minutes", declineLabel: "Already insured" },
    copy: { title: "New car? Make sure it's insured", body: "We saw {amount} paid to {merchant}. Third-party liability insurance is mandatory in Belgium before you drive. Want a quote?" },
  },
  {
    id: "credit_card_upsell", name: "Gold card upgrade", branch: "daily", kind: "offer", commercial: true, guardrail: "self_serve",
    triggers: [{ watcher: "income_change", direction: "up" }],
    hard: [{ type: "age_min", value: 18 }, { type: "not_product", product: "credit_card" }, { type: "income_min", value: 1500 }],
    soft: ["Income went up"], requires: ["current_account"], unlocks: [], conflicts: [],
    procedure: ["Credit check", "Card order"], freedoms: ["limit"],
    customerValue: 0.15, kbcValue: 0.8, urgency: 0.3,
    component: { type: "confirm", confirmLabel: "Upgrade", declineLabel: "No thanks" },
    copy: { title: "Upgrade to a Gold card", body: "Your income went up. Enjoy a higher limit and travel perks with a Gold card." },
  },
  {
    id: "raise_autosave", name: "Save part of a raise", branch: "savings", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "income_change", direction: "up" }],
    hard: [{ type: "age_min", value: 18 }], soft: ["No declared plan for the extra income"],
    requires: ["savings_account"], unlocks: ["investment_plan"], conflicts: [],
    procedure: ["Pick an amount", "Create a standing order to savings"], freedoms: ["amount", "day of month"],
    customerValue: 0.75, kbcValue: 0.25, urgency: 0.5,
    component: { type: "slider", label: "Move to savings every month", min: 0, max: 300, step: 10, value: 150, unit: "€", submitLabel: "Set it up" },
    copy: { title: "Your salary went up by {raise}", body: "Nice. Want to move part of it to savings automatically, before you get used to it?" },
  },
  {
    id: "investment_plan", name: "Investment advice", branch: "investing", kind: "advice", commercial: true, guardrail: "advisor",
    guardrailNote: "Investment advice falls under MiFID suitability rules: only a licensed advisor may recommend products.",
    triggers: [{ watcher: "savings_change" }, { watcher: "income_change", direction: "up" }],
    hard: [{ type: "age_min", value: 18 }, { type: "income_min", value: 2000 }],
    soft: ["Growing savings buffer", "Stable income"], requires: ["savings_account"], unlocks: [], conflicts: ["goals.home_purchase (short horizon)"],
    procedure: ["Suitability questionnaire", "Advisor conversation", "Proposal"], freedoms: ["risk profile", "monthly amount"],
    customerValue: 0.5, kbcValue: 0.7, urgency: 0.3,
    component: infoOk,
    copy: { title: "Talk to an advisor about investing?", body: "With your savings growing, an advisor can check whether investing part of it fits your goals and risk appetite." },
  },
  {
    id: "goal_check", name: "Savings goal", branch: "savings", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "savings_change" }],
    hard: [], soft: ["Saving rate jumped"], requires: [], unlocks: ["mortgage_simulation"], conflicts: [],
    procedure: ["Ask for the goal", "Track progress"], freedoms: ["target amount", "target date"],
    customerValue: 0.6, kbcValue: 0.2, urgency: 0.4,
    component: { type: "choice", options: [
      { id: "house", label: "A home" }, { id: "car", label: "A car" }, { id: "travel", label: "A big trip" }, { id: "private", label: "Rather not say" },
    ] },
    copy: { title: "You're saving {pct}% more each month", body: "Impressive. Saving for something specific? Tell us and we'll only bring up things that help with it." },
  },
  {
    id: "mortgage_simulation", name: "Mortgage simulation", branch: "home", kind: "offer", commercial: true, guardrail: "self_serve",
    triggers: [{ belief: "goals.home_purchase" }],
    hard: [{ type: "age_min", value: 18 }, { type: "income_min", value: 2500 }],
    soft: ["Home inspection or notary payments", "High savings rate"], requires: ["current_account"], unlocks: [], conflicts: [],
    procedure: ["Simulate borrowing capacity", "Book an appointment", "Credit file", "Offer"], freedoms: ["term", "fixed/variable", "own contribution"],
    customerValue: 0.85, kbcValue: 0.9, urgency: 0.7,
    component: { type: "confirm", confirmLabel: "Simulate my mortgage", declineLabel: "Not yet" },
    copy: { title: "Buying a home?", body: "It looks like you're preparing to buy a home. A 5-minute simulation shows what you can borrow and the monthly cost. No commitment." },
  },
  {
    id: "duplicate_refund", name: "Duplicate payment refund", branch: "daily", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "duplicate_payment" }],
    hard: [], soft: [], requires: [], unlocks: [], conflicts: [],
    procedure: ["Confirm with customer", "Request refund from payee"], freedoms: [],
    customerValue: 0.9, kbcValue: 0, urgency: 0.9,
    component: { type: "confirm", confirmLabel: "Yes, get it back", declineLabel: "It's correct" },
    copy: { title: "{merchant} charged you twice", body: "{amount} was debited twice within a day. Shall we ask for a refund?" },
  },
  {
    id: "energy_check", name: "Energy bill check", branch: "home", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "category_shift", category: "utilities", direction: "up" }],
    hard: [], soft: ["Fixed income", "Large relative increase"], requires: [], unlocks: [], conflicts: [],
    procedure: ["Explain the bill", "Compare contracts"], freedoms: [],
    customerValue: 0.65, kbcValue: 0, urgency: 0.6,
    component: { type: "choice", options: [
      { id: "explain", label: "Explain my new bill" }, { id: "compare", label: "Compare contracts" }, { id: "fine", label: "It's expected" },
    ] },
    copy: { title: "Your energy costs went up {pct}%", body: "You now pay about {recent} a month, against {baseline} before. Want help understanding it or comparing contracts?" },
  },
  {
    id: "health_cover", name: "Hospitalisation insurance", branch: "protection", kind: "offer", commercial: true, guardrail: "self_serve",
    triggers: [{ belief: "health.rising_costs" }],
    hard: [{ type: "age_min", value: 18 }, { type: "not_product", product: "hospital_insurance" }],
    soft: ["Rising health spending"], requires: [], unlocks: [], conflicts: [],
    procedure: ["Medical questionnaire", "Quote"], freedoms: ["room type", "deductible"],
    customerValue: 0.45, kbcValue: 0.6, urgency: 0.35,
    component: { type: "confirm", confirmLabel: "Have someone call me", declineLabel: "No thanks" },
    copy: { title: "Rising pharmacy costs", body: "Hospitalisation insurance can cover part of these costs. Want an advisor to call you?" },
  },
  {
    id: "estate_planning", name: "Gift & estate planning", branch: "investing", kind: "advice", commercial: false, guardrail: "advisor",
    guardrailNote: "Estate and gift planning is personal tax advice: routed to a human advisor.",
    triggers: [{ belief: "household.family_support" }],
    hard: [{ type: "age_min", value: 18 }], soft: ["Large gift to family", "Retirement age"], requires: [], unlocks: [], conflicts: [],
    procedure: ["Advisor call", "Explain gift registration options"], freedoms: [],
    customerValue: 0.8, kbcValue: 0.3, urgency: 0.5,
    component: infoOk,
    copy: { title: "About your gift to {merchant}", body: "Registering a gift can make a big difference to taxes later. An advisor can explain your options in a short call." },
  },
  {
    id: "low_buffer_alert", name: "Low balance heads-up", branch: "budgeting", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "low_buffer" }],
    hard: [], soft: [], requires: [], unlocks: [], conflicts: [],
    procedure: ["Warn", "Offer a transfer from savings"], freedoms: [],
    customerValue: 0.8, kbcValue: 0, urgency: 0.8,
    component: { type: "confirm", confirmLabel: "Move €300 from savings", declineLabel: "I'm fine" },
    copy: { title: "Heads-up: your balance is {balance}", body: "Some fixed costs are still due before payday. Want to move €300 from your savings to be safe?" },
  },
  {
    id: "child_savings", name: "Child savings account", branch: "savings", kind: "offer", commercial: true, guardrail: "self_serve",
    triggers: [{ belief: "household.children" }],
    hard: [{ type: "age_min", value: 18 }], soft: ["Young child in the household"], requires: ["current_account"], unlocks: [], conflicts: [],
    procedure: ["Open account for child", "Set up monthly transfer"], freedoms: ["monthly amount"],
    customerValue: 0.4, kbcValue: 0.6, urgency: 0.2,
    component: { type: "confirm", confirmLabel: "Tell me more", declineLabel: "Not for me" },
    copy: { title: "Start saving for your little one?", body: "A child savings account with a small monthly transfer adds up by the time they turn 18." },
  },
  {
    id: "rule_alert", name: "Your own rule", branch: "budgeting", kind: "help", commercial: false, guardrail: "self_serve",
    triggers: [{ watcher: "user_rule" }],
    hard: [], soft: ["Customer explicitly asked for this"], requires: [], unlocks: [], conflicts: [],
    procedure: ["Notify"], freedoms: [],
    customerValue: 1, kbcValue: 0, urgency: 1,
    component: infoOk,
    copy: { title: "{ruleLabel}", body: "{detail}" },
  },
];

export const NODE_BY_ID = new Map(SERVICE_GRAPH.map((n) => [n.id, n]));
